# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cf63d70f09543ddff3db9c3fede3d03999f24b76e31ad01f593e508ebc9913c7d1f973a454ce738e3af345fa819649343aeefb70248b5db3dab6110a50cea1b

test:
  secret_key_base: 0de73fb27c53ba4d7d0decd864038331c0b599400bbebddf6fa5a6daf1fc829c137688c5bcd5faf0d146ab637c85a0bee55f3d12c0d0e2cbb37e7e006f67c550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
